FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libpq-dev && rm -rf /var/lib/apt/lists/*

COPY pipeline/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m spacy download en_core_web_sm

COPY pipeline/ ./pipeline/
COPY db/ ./db/
COPY airflow/ ./airflow/

ENV PYTHONPATH=/app

CMD ["python", "-m", "pipeline.orchestrator"]
