const SAMPLE_STATES = [
  { state: 'AL', top_word: 'football', dominant_sentiment: 'positive', sentiment_avg: 0.15, post_volume: 145, category: 'cultural', tags: ['cultural'] },
  { state: 'AK', top_word: 'wilderness', dominant_sentiment: 'positive', sentiment_avg: 0.22, post_volume: 42, category: 'identity', tags: ['identity'] },
  { state: 'AZ', top_word: 'drought', dominant_sentiment: 'negative', sentiment_avg: -0.12, post_volume: 198, category: 'civic', tags: ['civic'] },
  { state: 'AR', top_word: 'barbecue', dominant_sentiment: 'positive', sentiment_avg: 0.18, post_volume: 67, category: 'food ritual', tags: ['food ritual'] },
  { state: 'CA', top_word: 'housing', dominant_sentiment: 'negative', sentiment_avg: -0.08, post_volume: 892, category: 'civic', tags: ['civic'] },
  { state: 'CO', top_word: 'trails', dominant_sentiment: 'positive', sentiment_avg: 0.31, post_volume: 234, category: 'cultural', tags: ['cultural'] },
  { state: 'CT', top_word: 'commute', dominant_sentiment: 'negative', sentiment_avg: -0.14, post_volume: 89, category: 'social behavior', tags: ['social behavior'] },
  { state: 'DE', top_word: 'beach', dominant_sentiment: 'positive', sentiment_avg: 0.25, post_volume: 34, category: 'cultural', tags: ['cultural'] },
  { state: 'FL', top_word: 'hurricane', dominant_sentiment: 'negative', sentiment_avg: -0.22, post_volume: 567, category: 'civic', tags: ['civic'] },
  { state: 'GA', top_word: 'peach', dominant_sentiment: 'positive', sentiment_avg: 0.19, post_volume: 312, category: 'identity', tags: ['identity'] },
  { state: 'HI', top_word: 'aloha', dominant_sentiment: 'positive', sentiment_avg: 0.42, post_volume: 78, category: 'heritage', tags: ['heritage'] },
  { state: 'ID', top_word: 'potato', dominant_sentiment: 'positive', sentiment_avg: 0.11, post_volume: 45, category: 'identity', tags: ['identity'] },
  { state: 'IL', top_word: 'pizza', dominant_sentiment: 'positive', sentiment_avg: 0.16, post_volume: 445, category: 'food ritual', tags: ['food ritual'] },
  { state: 'IN', top_word: 'racing', dominant_sentiment: 'positive', sentiment_avg: 0.21, post_volume: 156, category: 'cultural', tags: ['cultural'] },
  { state: 'IA', top_word: 'corn', dominant_sentiment: 'neutral', sentiment_avg: 0.03, post_volume: 62, category: 'identity', tags: ['identity'] },
  { state: 'KS', top_word: 'tornado', dominant_sentiment: 'negative', sentiment_avg: -0.18, post_volume: 88, category: 'civic', tags: ['civic'] },
  { state: 'KY', top_word: 'bourbon', dominant_sentiment: 'positive', sentiment_avg: 0.28, post_volume: 134, category: 'heritage', tags: ['heritage'] },
  { state: 'LA', top_word: 'crawfish', dominant_sentiment: 'positive', sentiment_avg: 0.35, post_volume: 267, category: 'food ritual', tags: ['food ritual'] },
  { state: 'ME', top_word: 'lobster', dominant_sentiment: 'positive', sentiment_avg: 0.24, post_volume: 56, category: 'food ritual', tags: ['food ritual'] },
  { state: 'MD', top_word: 'crab', dominant_sentiment: 'positive', sentiment_avg: 0.19, post_volume: 178, category: 'food ritual', tags: ['food ritual'] },
  { state: 'MA', top_word: 'wicked', dominant_sentiment: 'positive', sentiment_avg: 0.12, post_volume: 389, category: 'dialect', tags: ['dialect'] },
  { state: 'MI', top_word: 'lakes', dominant_sentiment: 'positive', sentiment_avg: 0.20, post_volume: 234, category: 'identity', tags: ['identity'] },
  { state: 'MN', top_word: 'hotdish', dominant_sentiment: 'positive', sentiment_avg: 0.17, post_volume: 167, category: 'food ritual', tags: ['food ritual'] },
  { state: 'MS', top_word: 'blues', dominant_sentiment: 'positive', sentiment_avg: 0.14, post_volume: 54, category: 'heritage', tags: ['heritage'] },
  { state: 'MO', top_word: 'gateway', dominant_sentiment: 'neutral', sentiment_avg: 0.04, post_volume: 189, category: 'identity', tags: ['identity'] },
  { state: 'MT', top_word: 'ranch', dominant_sentiment: 'positive', sentiment_avg: 0.23, post_volume: 38, category: 'heritage', tags: ['heritage'] },
  { state: 'NE', top_word: 'husker', dominant_sentiment: 'positive', sentiment_avg: 0.26, post_volume: 72, category: 'identity', tags: ['identity'] },
  { state: 'NV', top_word: 'desert', dominant_sentiment: 'neutral', sentiment_avg: 0.01, post_volume: 145, category: 'identity', tags: ['identity'] },
  { state: 'NH', top_word: 'maple', dominant_sentiment: 'positive', sentiment_avg: 0.21, post_volume: 41, category: 'heritage', tags: ['heritage'] },
  { state: 'NJ', top_word: 'diner', dominant_sentiment: 'positive', sentiment_avg: 0.09, post_volume: 234, category: 'cultural', tags: ['cultural'] },
  { state: 'NM', top_word: 'chile', dominant_sentiment: 'positive', sentiment_avg: 0.27, post_volume: 67, category: 'food ritual', tags: ['food ritual'] },
  { state: 'NY', top_word: 'bodega', dominant_sentiment: 'positive', sentiment_avg: 0.08, post_volume: 756, category: 'cultural', tags: ['cultural'] },
  { state: 'NC', top_word: 'barbecue', dominant_sentiment: 'positive', sentiment_avg: 0.22, post_volume: 245, category: 'food ritual', tags: ['food ritual'] },
  { state: 'ND', top_word: 'prairie', dominant_sentiment: 'positive', sentiment_avg: 0.15, post_volume: 28, category: 'identity', tags: ['identity'] },
  { state: 'OH', top_word: 'buckeye', dominant_sentiment: 'positive', sentiment_avg: 0.18, post_volume: 278, category: 'identity', tags: ['identity'] },
  { state: 'OK', top_word: 'rodeo', dominant_sentiment: 'positive', sentiment_avg: 0.20, post_volume: 98, category: 'heritage', tags: ['heritage'] },
  { state: 'OR', top_word: 'hiking', dominant_sentiment: 'positive', sentiment_avg: 0.33, post_volume: 189, category: 'cultural', tags: ['cultural'] },
  { state: 'PA', top_word: 'jawn', dominant_sentiment: 'positive', sentiment_avg: 0.10, post_volume: 345, category: 'dialect', tags: ['dialect'] },
  { state: 'RI', top_word: 'clambake', dominant_sentiment: 'positive', sentiment_avg: 0.26, post_volume: 32, category: 'food ritual', tags: ['food ritual'] },
  { state: 'SC', top_word: 'grits', dominant_sentiment: 'positive', sentiment_avg: 0.21, post_volume: 112, category: 'food ritual', tags: ['food ritual'] },
  { state: 'SD', top_word: 'rushmore', dominant_sentiment: 'positive', sentiment_avg: 0.19, post_volume: 24, category: 'heritage', tags: ['heritage'] },
  { state: 'TN', top_word: 'country', dominant_sentiment: 'positive', sentiment_avg: 0.24, post_volume: 278, category: 'cultural', tags: ['cultural'] },
  { state: 'TX', top_word: 'howdy', dominant_sentiment: 'positive', sentiment_avg: 0.16, post_volume: 623, category: 'identity', tags: ['identity'] },
  { state: 'UT', top_word: 'canyon', dominant_sentiment: 'positive', sentiment_avg: 0.29, post_volume: 112, category: 'identity', tags: ['identity'] },
  { state: 'VT', top_word: 'syrup', dominant_sentiment: 'positive', sentiment_avg: 0.23, post_volume: 36, category: 'heritage', tags: ['heritage'] },
  { state: 'VA', top_word: 'history', dominant_sentiment: 'positive', sentiment_avg: 0.13, post_volume: 198, category: 'heritage', tags: ['heritage'] },
  { state: 'WA', top_word: 'coffee', dominant_sentiment: 'positive', sentiment_avg: 0.14, post_volume: 312, category: 'cultural', tags: ['cultural'] },
  { state: 'WV', top_word: 'mountain', dominant_sentiment: 'positive', sentiment_avg: 0.18, post_volume: 56, category: 'identity', tags: ['identity'] },
  { state: 'WI', top_word: 'cheese', dominant_sentiment: 'positive', sentiment_avg: 0.25, post_volume: 178, category: 'food ritual', tags: ['food ritual'] },
  { state: 'WY', top_word: 'frontier', dominant_sentiment: 'positive', sentiment_avg: 0.20, post_volume: 22, category: 'heritage', tags: ['heritage'] },
];

export const MOCK_MAP_TODAY = {
  date: new Date().toISOString().split('T')[0],
  states: SAMPLE_STATES,
};

export const MOCK_LEADERBOARD = {
  leaderboard: [
    { word: 'barbecue', total_frequency: 1245, avg_distinctiveness: 0.082, state_count: 12, avg_sentiment: 0.21 },
    { word: 'housing', total_frequency: 1102, avg_distinctiveness: 0.078, state_count: 18, avg_sentiment: -0.11 },
    { word: 'football', total_frequency: 987, avg_distinctiveness: 0.071, state_count: 22, avg_sentiment: 0.19 },
    { word: 'coffee', total_frequency: 876, avg_distinctiveness: 0.065, state_count: 15, avg_sentiment: 0.14 },
    { word: 'hurricane', total_frequency: 734, avg_distinctiveness: 0.061, state_count: 8, avg_sentiment: -0.25 },
    { word: 'pizza', total_frequency: 698, avg_distinctiveness: 0.058, state_count: 10, avg_sentiment: 0.18 },
    { word: 'howdy', total_frequency: 567, avg_distinctiveness: 0.055, state_count: 4, avg_sentiment: 0.16 },
    { word: 'bodega', total_frequency: 523, avg_distinctiveness: 0.052, state_count: 3, avg_sentiment: 0.08 },
    { word: 'wicked', total_frequency: 489, avg_distinctiveness: 0.049, state_count: 5, avg_sentiment: 0.12 },
    { word: 'crawfish', total_frequency: 445, avg_distinctiveness: 0.047, state_count: 4, avg_sentiment: 0.35 },
    { word: 'grits', total_frequency: 412, avg_distinctiveness: 0.044, state_count: 6, avg_sentiment: 0.21 },
    { word: 'bourbon', total_frequency: 389, avg_distinctiveness: 0.042, state_count: 5, avg_sentiment: 0.28 },
    { word: 'aloha', total_frequency: 356, avg_distinctiveness: 0.089, state_count: 2, avg_sentiment: 0.42 },
    { word: 'jawn', total_frequency: 334, avg_distinctiveness: 0.086, state_count: 2, avg_sentiment: 0.10 },
    { word: 'drought', total_frequency: 312, avg_distinctiveness: 0.041, state_count: 7, avg_sentiment: -0.15 },
  ],
};

export const MOCK_WORD_CHANGES = {
  changes: [
    { state: 'CA', current_word: 'housing', previous_word: 'wildfire', date: new Date().toISOString() },
    { state: 'FL', current_word: 'hurricane', previous_word: 'beach', date: new Date().toISOString() },
    { state: 'NY', current_word: 'bodega', previous_word: 'subway', date: new Date().toISOString() },
  ],
};

export const MOCK_PIPELINE_STATUS = {
  lastRun: { completed_at: new Date(Date.now() - 3 * 3600000).toISOString(), duration_seconds: 894.9, status: 'success' },
  todayTasks: [
    { task_name: 'ingest_reddit', status: 'success', rows_processed: 4523, errors: 2, duration_seconds: 145.3, completed_at: new Date().toISOString() },
    { task_name: 'ingest_mastodon', status: 'success', rows_processed: 876, errors: 0, duration_seconds: 89.1, completed_at: new Date().toISOString() },
    { task_name: 'clean_and_tokenize', status: 'success', rows_processed: 6633, errors: 0, duration_seconds: 234.7, completed_at: new Date().toISOString() },
    { task_name: 'sentiment_analysis', status: 'success', rows_processed: 6633, errors: 0, duration_seconds: 178.2, completed_at: new Date().toISOString() },
    { task_name: 'word_scoring', status: 'success', rows_processed: 12500, errors: 0, duration_seconds: 56.8, completed_at: new Date().toISOString() },
    { task_name: 'full_pipeline', status: 'success', rows_processed: 0, errors: 3, duration_seconds: 894.9, completed_at: new Date().toISOString() },
  ],
  dataFreshness: new Date(Date.now() - 3 * 3600000).toISOString(),
};
